baseURL = "/"
languageCode = "en-us"
title = "Lumi's Tech Blog"
theme = "ananke"

taxonomies = { category = "categories", tag = "tags", series = "series" }

[params]
  author = "Lumi"
  description = "Tech notes and tutorials"
  site_logo = "images/lumi-blog.jpg"
  avatar = "images/lumi-blog.jpg"
  background_color_class = "bg-light-gray"
  featured_image = "images/lumi-blog.jpg"
