baseURL = "https://Lumicreator.github.io/lumi-tech-blog/"
languageCode = "en-us"
title = "Lumi's Tech Blog"
theme = "ananke"

taxonomies = { category = "categories", tag = "tags", series = "series" }

[params]
  author = "Lumi"
  description = "Tech notes and tutorials"
  background_color_class = "bg-near-black"
  featured_image = "images/blog-bg.jpg"
  recent_posts_number = 10
